// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var bodyParser, database, express, jsonParser, server;

  database = require('./database');

  express = require('express');

  bodyParser = require('body-parser');

  server = express();

  jsonParser = bodyParser.json();

  server.post('/', jsonParser, function(req, res) {
    var content, level, match, sender;
    sender = req.body.sender || '神秘骇客';
    level = req.body.level || 999;
    content = req.body.content || '神秘消息';
    match = req.body.match || '神奇对决';
    return database.saveMessage(sender, content, level, match, function(result) {
      res.statusCode = result ? 200 : 500;
      return res.end('ok');
    });
  });

  server.listen(1984);

}).call(this);

//# sourceMappingURL=server.js.map
