// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var bodyParser, database, express, server;

  database = require('./database');

  express = require('express');

  bodyParser = require('body-parser');

  server = express();

  server.use(bodyParser.urlencoded({
    extended: false
  }));

  server.post('/', function(req, res) {
    var content, ip, level, match, sender;
    console.log(req.body);
    sender = req.body.sender || '神秘骇客';
    level = req.body.level || 999;
    content = req.body.content || '神秘消息';
    match = req.body.match || '神奇对决';
    ip = req.body.ip || '0.0.0.0';
    return database.saveMessage(sender, content, level, match, ip, function(result) {
      res.statusCode = result ? 200 : 500;
      return res.end('ok');
    });
  });

  server.listen(1984);

}).call(this);

//# sourceMappingURL=server.js.map
